// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhsynwxoejulkrotpiij.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhoc3lud3hvZWp1bGtyb3RwaWlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgyMjQwOTcsImV4cCI6MjA1MzgwMDA5N30.g7SQ1HsAdywZxvM4jCNl35cIS8_e-xUvH0t-Jd73ktc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);